- src/components/popups/FindUsers/FindUsers.tsx
- src/utils/helpers.ts
Добавил функцию debounce в helpers.
Обернул поиск в сотрудников в debounce.
Не стал пользоваться функцией onDebounce компонента Search, чтобы не нарушать логику работы компонента. Добавил только обертку.
> [FIND USERS]

- src/components/atoms/Datepicker/Datepicker.scss
- src/components/atoms/Datepicker/Datepicker.tsx
https://trello.com/c/jAUP4In4/82-%D0%B8%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0-%D0%B4%D0%B5%D0%B9%D1%82%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%B0-%D0%BD%D0%B0%D0%BB%D0%B5%D0%B7%D0%B0%D0%B5%D1%82-%D0%BD%D0%B0-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D1%83
> feat: [Datepicker] move icons into input adornment

- src/components/atoms/Datepicker/Datepicker.tsx
- src/components/atoms/Input/Input.tsx
- src/components/atoms/Textarea/Textarea.scss
https://trello.com/c/KtBC9OUD/76-%D0%B2%D1%81%D0%B5-%D0%B8%D0%BD%D0%BF%D1%83%D1%82%D1%8B-%D0%B8-%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%BD%D1%8B%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D1%8B-%D0%B1%D1%8B%D1%82%D1%8C-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E-%D0%B1%D0%B5%D0%BB%D1%8B%D0%B5-%D1%81%D0%B5%D0%B9%D1%87%D0%B0%D1%81-%D0%BF%D1%80%D0%BE%D0%B7%D1%80%D0%B0%D1%87%D0%BD%D1%8B%D0%B5
> feat: [Input] set filled by default

- src/components/atoms/InputFile/InputFile.scss
https://trello.com/c/TJ9tWFv6/81-inputfile-%D0%BD%D0%B5-%D1%85%D0%B2%D0%B0%D1%82%D0%B0%D0%B5%D1%82-flex-wrap-%D1%84%D0%B0%D0%B9%D0%BB%D1%8B-%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D1%8B%D0%B2%D0%B0%D1%8E%D1%82%D1%81%D1%8F-%D0%B2-%D0%BE%D0%B4%D0%BD%D1%83-%D1%81%D1%82%D1%80%D0%BE%D1%87%D0%BA%D1%83
> fix: [InputFile] add flex wrap for chips

- src/components/molecules/Card/Card.scss
https://trello.com/c/XCbKCQrL/84-card
> feat: [Card] add hover

- src/components/atoms/InputFile/InputFile.tsx
- src/components/molecules/History/History.scss
- src/types/index.ts
- src/utils/helpers.ts
Добавил id в тип IFileDate.
Добавил второй метод скачивания в InputFile. Если есть id (который всегда приходит с бэка), то файл скачивается через сервер. Если ID нет, значит файл лежит в локальном стейте и его можно скачать через base64 и blob.
> [INPUT FILE]

- src/components/molecules/EntityCard/EntityCard.tsx
https://trello.com/c/eQJ0iGQE/87-card-%D0%BF%D1%80%D0%B8-%D0%BA%D0%BB%D0%B8%D0%BA%D0%B5-%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%82%D0%B0%D0%B1%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%B0-%D0%BD%D0%B5-%D0%BF%D1%80%D0%B5%D0%B2%D0%B5%D0%BD%D1%82%D0%B8%D1%82%D1%81%D1%8F-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%BA%D0%BB%D0%B8%D0%BA%D0%B0
> fix: [EntityCard] stop propagation of copy click event

- src/components/atoms/InputFile/InputFile.spec.tsx
- src/components/atoms/InputFile/InputFile.stories.tsx
- src/components/atoms/InputFile/InputFile.tsx
- src/components/molecules/CommentTile/CommentTile.spec.tsx
- src/components/molecules/PDFViewer/PDFViewer.tsx
- src/components/organisms/Signification/Signification.tsx
- src/utils/download.ts
- src/utils/helpers.ts
Добавил в функцию download условия для скачивания и обработку ошибок.
> [DOWNLOAD]

- src/components/atoms/Select/Select.tsx
Добавил проверку на пустой контент в Select 
В компоненте Menu такой проблемы нет (или не увидел хех)
> feat: [dropdown] dropdown empty content

- src/components/atoms/Checkbox/Checkbox.scss
- src/components/atoms/Modal/Modal.scss
- src/components/popups/FindEntities/FindEntities.scss
- src/components/popups/FindEntities/FindEntities.spec.tsx
- src/components/popups/FindEntities/FindEntities.stories.tsx
- src/components/popups/FindEntities/FindEntities.tsx
- src/components/popups/FindEntities/index.ts
- src/components/popups/FindEntitiesPosition/FindEntitiesPosition.scss
- src/components/popups/FindEntitiesPosition/FindEntitiesPosition.tsx
- src/components/popups/FindEntitiesPosition/index.ts
- src/components/popups/FindEntitiesPosition/positions.mocks.ts
- src/components/popups/FindEntitiesUser/FindEntitiesUser.scss
- src/components/popups/FindEntitiesUser/FindEntitiesUser.tsx
- src/components/popups/FindEntitiesUser/createGetUsers.ts
- src/components/popups/FindEntitiesUser/findUsers.ts
- src/components/popups/FindEntitiesUser/index.ts
- src/components/popups/FindEntitiesUser/users.mocks.ts
- src/index.ts
https://trello.com/c/0A6jdRJp/47-find-users
> feat: [FindEntities] add component

- src/components/atoms/Tooltip/ArrowTooltipIcon.tsx
- src/components/atoms/Tooltip/Tooltip.scss
- src/components/atoms/Tooltip/TooltipContent.tsx
https://trello.com/c/2GFef42X/135-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-popupa-%D0%B2-%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%BD%D1%8B%D1%85-%D1%83%D1%81%D0%BB%D0%BE%D0%B2%D0%B8%D1%8F%D1%85
> Отображение стрелочки тултипа в граничных условиях

- src/components/atoms/Input/Input.tsx
- src/components/atoms/Search/Search.tsx
- src/components/popups/FindEntities/FindEntities.spec.tsx
- src/components/popups/FindEntities/FindEntities.tsx
- src/hooks/useDebounce.ts
- src/hooks/useLatest.ts
- src/index.ts
https://trello.com/c/ob7waTwH/139-input-ondebounce-%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B5-%D1%81-pattern
> feat: rework debounce for Search and Input

- src/components/atoms/Tabs/Tabs.scss
- src/components/atoms/Tabs/Tabs.stories.tsx
- src/components/atoms/Tabs/Tabs.tsx
https://trello.com/c/rGWaNpjE/186-tab-%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80
> feat: [Tabs] add small size

- src/components/atoms/Tabs/Tabs.stories.tsx
- src/components/atoms/Tabs/mock.tsx
- src/components/atoms/Unread/Unread.scss
- src/components/atoms/Unread/Unread.tsx
- src/components/atoms/Unread/index.ts
- src/index.ts
https://trello.com/c/eXQDKoW7/177-tab-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8
> feat: [Tabs] add Unread component

- src/components/atoms/Chip/Chip.scss
- src/components/atoms/Chip/Chip.spec.tsx
- src/components/atoms/Chip/Chip.stories.tsx
- src/components/atoms/Chip/Chip.tsx
- src/components/atoms/Datepicker/Datepicker.stories.tsx
- src/components/atoms/Select/Select.tsx
https://trello.com/c/MQUxIYCW/178-chips-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8
> feat: [Chip] update styles

- src/components/atoms/Link/Link.scss
- src/components/atoms/Link/Link.spec.tsx
- src/components/atoms/Link/Link.stories.tsx
- src/components/atoms/Link/Link.tsx
- src/components/atoms/Link/index.ts
https://trello.com/c/eTl96aeQ/190-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-link
> feat: [Link] add new component

- src/components/atoms/Accordion/Accordion.scss
- src/components/atoms/Accordion/Accordion.tsx
- src/components/atoms/Accordion/AccordionItem.tsx
https://trello.com/c/akytqk5S/179-accordion-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8
> feat: [Accordion] update styles

- src/components/atoms/Segment/Segment.scss
- src/components/atoms/Segment/Segment.spec.tsx
- src/components/atoms/Segment/Segment.stories.tsx
- src/components/atoms/Segment/Segment.tsx
- src/components/atoms/Segment/mock.tsx
- src/types/index.ts
https://trello.com/c/i9rqVjs4/176-segment-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8
> feat: [Segment] update styles

- src/components/atoms/Input/Input.stories.tsx
https://trello.com/b/EAlHKKTB/%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%BE%D0%B2
> feat: [Input] add readOnly styles

- src/components/atoms/Button/Button.scss
- src/components/atoms/Hint/Hint.scss
- src/components/atoms/Hint/Hint.spec.tsx
- src/components/atoms/Hint/Hint.stories.tsx
- src/components/atoms/Hint/Hint.tsx
- src/styles/mixins.scss
https://trello.com/c/gxSoB6LC/182-notification-%D0%B4%D0%BE%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8
> feat: [Hint] update styles

- src/components/molecules/Layout/Layout.context.ts
- src/components/molecules/Layout/Layout.scss
- src/components/molecules/Layout/Layout.spec.tsx
- src/components/molecules/Layout/Layout.stories.tsx
- src/components/molecules/Layout/Layout.tsx
- src/components/molecules/Layout/LayoutColumn/LayoutColumn.scss
- src/components/molecules/Layout/LayoutColumn/LayoutColumn.tsx
- src/components/molecules/Layout/LayoutColumn/index.ts
- src/components/molecules/Layout/index.ts
- src/index.ts
https://trello.com/c/PbKqYpmN/148-layouts-%D0%BD%D0%BE%D0%B2%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B
> feat: [Layout] add new component
